"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { AppShell, DemoNotice, PageHeading } from "@/components/layout/app-shell";
import { ArrowRight, Check, CheckCircle2, FileSpreadsheet, FileUp, RotateCcw, Upload, X } from "lucide-react";
import { useAuth } from "@/lib/auth/session";

type Stage = "upload" | "preview" | "complete";
export function ImportWorkflow() {
  const [stage, setStage] = useState<Stage>("upload");
  const [file, setFile] = useState<File | null>(null);
  const { notify } = useAuth();
  useEffect(() => { if (stage === "complete") notify("Assessment imported", "Three illustrative rows were added to the demo view."); }, [stage, notify]);
  const input = useRef<HTMLInputElement>(null);
  const selectFile = (next?: File) => { if (next) { setFile(next); setStage("preview"); } };
  return <AppShell><DemoNotice /><PageHeading eyebrow="VALIDATED DATA IMPORT" title="Bring your assessment data." description="Review a structured preview before confirming any assessment records." actions={<Link className="button button-secondary" href="/assessments">Assessment records <ArrowRight size={14} /></Link>} />
    <div className="import-steps"><div className={`import-step ${stage === "upload" ? "current" : "done"}`}><span>{stage === "upload" ? "01" : <Check size={14} />}</span>Choose file</div><i /><div className={`import-step ${stage === "preview" ? "current" : stage === "complete" ? "done" : ""}`}><span>{stage === "complete" ? <Check size={14} /> : "02"}</span>Validate & review</div><i /><div className={`import-step ${stage === "complete" ? "current" : ""}`}><span>03</span>Confirm records</div></div>
    <section className="panel import-panel">{stage === "upload" && <><div className="import-intro"><span className="import-icon"><FileSpreadsheet size={20} /></span><div><span className="panel-kicker">STEP 01 · SELECT SOURCE</span><h2>Choose a marksheet to review</h2><p>Start with a CSV or Excel spreadsheet. Your data stays unconfirmed until you review the preview.</p></div></div><button className="upload-zone" onClick={() => input.current?.click()} onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); selectFile(e.dataTransfer.files[0]); }}><span className="upload-symbol"><FileUp size={21} /></span><b>Drop your file here, or <u>browse files</u></b><small>CSV or Excel · up to 10 MB</small></button><input ref={input} hidden type="file" accept=".csv,.xlsx,.xls" onChange={(e) => selectFile(e.target.files?.[0])} /><div className="import-guidance"><div><b>Suggested columns</b><span>Student ID · Assessment · Score · Maximum score</span></div><Link href="/assessments">View assessment records <ArrowRight size={13} /></Link></div></>}
      {stage === "preview" && <><div className="import-intro"><span className="import-icon"><FileSpreadsheet size={20} /></span><div><span className="panel-kicker">STEP 02 · REVIEW PREVIEW</span><h2>Check your assessment rows</h2><p>{file?.name} · {file ? (file.size / 1024).toFixed(0) : 0} KB · Demo preview</p></div><button className="icon-action import-clear" aria-label="Remove selected file" onClick={() => { setFile(null); setStage("upload"); }}><X size={16} /></button></div><div className="validation-summary"><div><CheckCircle2 size={17} /><span><b>3 rows ready</b><small>Preview rows are illustrative; the demo does not parse file contents.</small></span></div><span className="validation-warning">Connect backend to validate actual file data</span></div><div className="table-scroll import-preview-table"><table><thead><tr><th>ROW</th><th>STUDENT ID</th><th>ASSESSMENT</th><th>SCORE</th><th>MAXIMUM</th><th>STATUS</th></tr></thead><tbody>{[["01", "STU-2041", "Mid-semester", "78", "100"], ["02", "STU-1982", "Mid-semester", "42", "100"], ["03", "STU-2136", "Mid-semester", "38", "100"]].map((row) => <tr key={row[0]}>{row.map((value) => <td key={value}>{value}</td>)}<td><span className="status-tag status-good"><i /> Ready</span></td></tr>)}</tbody></table></div><div className="import-actions"><button className="button button-secondary" onClick={() => { setStage("upload"); setFile(null); }}><RotateCcw size={15} /> Choose another file</button><button className="button button-primary" onClick={() => setStage("complete")}>Confirm demo import <ArrowRight size={15} /></button></div></>}
      {stage === "complete" && <div className="import-complete"><span><CheckCircle2 size={26} /></span><span className="panel-kicker">DEMO IMPORT COMPLETE</span><h2>Your preview is ready.</h2><p>Three fictional assessment rows were added to the demo experience. Connect the import API to validate and persist real records.</p><div><Link className="button button-primary" href="/assessments">Review assessments <ArrowRight size={15} /></Link><button className="button button-secondary" onClick={() => { setStage("upload"); setFile(null); }}>Import another <Upload size={15} /></button></div></div>}</section>
    <div className="import-safety"><CheckCircle2 size={15} /><span><b>Review before you confirm.</b> The production import flow should validate columns, flag row errors, and report duplicate records without silently changing existing data.</span></div>
  </AppShell>;
}
