"""Students, section history (one open entry per student), enrolments (drop keeps row).

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-26
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "students",
        sa.Column("register_number", sa.String(length=20), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("department_id", sa.Uuid(), nullable=False),
        sa.Column("batch_year", sa.Integer(), nullable=False),
        sa.Column("current_section_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "register_number ~ '^[A-Z0-9]{5,20}$'", name=op.f("ck_students_register_number_format")
        ),
        sa.CheckConstraint(
            "batch_year BETWEEN 2000 AND 2100", name=op.f("ck_students_batch_year_range")
        ),
        sa.CheckConstraint(
            "email IS NULL OR email = lower(btrim(email))",
            name=op.f("ck_students_email_normalised"),
        ),
        sa.CheckConstraint("length(full_name) > 0", name=op.f("ck_students_full_name_not_blank")),
        sa.ForeignKeyConstraint(
            ["current_section_id"],
            ["sections.id"],
            name=op.f("fk_students_current_section_id_sections"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_students_department_id_departments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_students")),
        sa.UniqueConstraint("email", name=op.f("uq_students_email")),
        sa.UniqueConstraint("register_number", name=op.f("uq_students_register_number")),
    )
    op.create_index(
        op.f("ix_students_current_section_id"), "students", ["current_section_id"], unique=False
    )
    op.create_index(op.f("ix_students_department_id"), "students", ["department_id"], unique=False)
    op.create_table(
        "enrollments",
        sa.Column("offering_id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "DROPPED", name="enrollment_status"),
            server_default="ACTIVE",
            nullable=False,
        ),
        sa.Column(
            "enrolled_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("dropped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "(status = 'DROPPED') = (dropped_at IS NOT NULL)",
            name=op.f("ck_enrollments_dropped_at_matches_status"),
        ),
        sa.ForeignKeyConstraint(
            ["offering_id"],
            ["course_offerings.id"],
            name=op.f("fk_enrollments_offering_id_course_offerings"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_enrollments_student_id_students"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_enrollments")),
        sa.UniqueConstraint(
            "offering_id", "student_id", name=op.f("uq_enrollments_offering_id_student_id")
        ),
    )
    op.create_index(
        op.f("ix_enrollments_offering_id"), "enrollments", ["offering_id"], unique=False
    )
    op.create_index(op.f("ix_enrollments_student_id"), "enrollments", ["student_id"], unique=False)
    op.create_table(
        "student_section_history",
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("section_id", sa.Uuid(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "ended_at IS NULL OR ended_at >= started_at",
            name=op.f("ck_student_section_history_period_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
            name=op.f("fk_student_section_history_section_id_sections"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_student_section_history_student_id_students"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_section_history")),
    )
    op.create_index(
        op.f("ix_student_section_history_student_id"),
        "student_section_history",
        ["student_id"],
        unique=False,
    )
    op.create_index(
        "uq_student_section_history_open",
        "student_section_history",
        ["student_id"],
        unique=True,
        postgresql_where=sa.text("ended_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_student_section_history_open",
        table_name="student_section_history",
        postgresql_where=sa.text("ended_at IS NULL"),
    )
    op.drop_index(
        op.f("ix_student_section_history_student_id"), table_name="student_section_history"
    )
    op.drop_table("student_section_history")
    op.drop_index(op.f("ix_enrollments_student_id"), table_name="enrollments")
    op.drop_index(op.f("ix_enrollments_offering_id"), table_name="enrollments")
    op.drop_table("enrollments")
    op.drop_index(op.f("ix_students_department_id"), table_name="students")
    op.drop_index(op.f("ix_students_current_section_id"), table_name="students")
    op.drop_table("students")
    sa.Enum(name="enrollment_status").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
