"""Import staging/history (import_batches) and result provenance
(assessment_results.import_batch_id).

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-26
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_batches",
        sa.Column("offering_id", sa.Uuid(), nullable=False),
        sa.Column("assessment_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("previewed", "committed", "discarded", name="import_status"),
            server_default="previewed",
            nullable=False,
        ),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_type", sa.String(length=8), nullable=False),
        sa.Column("file_sha256", sa.String(length=64), nullable=False),
        sa.Column("file_format", sa.Enum("wide", "long", name="import_format"), nullable=False),
        sa.Column("sheet_name", sa.String(length=100), nullable=True),
        sa.Column("headers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rows", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("skipped_empty_rows", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("column_mapping", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("fixes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("excluded_rows", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("total_rows", sa.Integer(), nullable=False),
        sa.Column("uploaded_by_id", sa.Uuid(), nullable=True),
        sa.Column("committed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("committed_by_id", sa.Uuid(), nullable=True),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'committed') = (committed_at IS NOT NULL)",
            name=op.f("ck_import_batches_committed_at_matches"),
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
            name=op.f("fk_import_batches_assessment_id_assessments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["committed_by_id"],
            ["users.id"],
            name=op.f("fk_import_batches_committed_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["offering_id"],
            ["course_offerings.id"],
            name=op.f("fk_import_batches_offering_id_course_offerings"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"],
            ["users.id"],
            name=op.f("fk_import_batches_uploaded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_batches")),
    )
    op.create_index(
        op.f("ix_import_batches_file_sha256"), "import_batches", ["file_sha256"], unique=False
    )
    op.create_index(
        op.f("ix_import_batches_offering_id_created_at"),
        "import_batches",
        ["offering_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_import_batches_uploaded_by_id"), "import_batches", ["uploaded_by_id"], unique=False
    )
    op.add_column("assessment_results", sa.Column("import_batch_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_assessment_results_import_batch_id"),
        "assessment_results",
        ["import_batch_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_assessment_results_import_batch_id_import_batches"),
        "assessment_results",
        "import_batches",
        ["import_batch_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_assessment_results_import_batch_id_import_batches"),
        "assessment_results",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_assessment_results_import_batch_id"), table_name="assessment_results")
    op.drop_column("assessment_results", "import_batch_id")
    op.drop_index(op.f("ix_import_batches_uploaded_by_id"), table_name="import_batches")
    op.drop_index(op.f("ix_import_batches_offering_id_created_at"), table_name="import_batches")
    op.drop_index(op.f("ix_import_batches_file_sha256"), table_name="import_batches")
    op.drop_table("import_batches")
    for enum_name in ("import_status", "import_format"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
