"""Assessments, assessment_results (score nullable; status present/absent/exempt),
department settings, audit_logs; course_offerings.pass_mark_percent -> pass_percent
(default 50) and config JSONB.

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-26
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings",
        sa.Column("department_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("key ~ '^[A-Za-z0-9_.-]{1,100}$'", name=op.f("ck_settings_key_format")),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_settings_department_id_departments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_settings_updated_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settings")),
        sa.UniqueConstraint("department_id", "key", name=op.f("uq_settings_department_id_key")),
    )
    op.create_table(
        "assessments",
        sa.Column("offering_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "assessment_type",
            sa.Enum(
                "CT", "FT", "QUIZ", "ASSIGNMENT", "LAB", "INTERNAL", "OTHER", name="assessment_type"
            ),
            nullable=False,
        ),
        sa.Column("assessment_date", sa.Date(), nullable=True),
        sa.Column("max_marks", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column(
            "weightage",
            sa.Numeric(precision=5, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("sequence_no", sa.Integer(), nullable=False),
        sa.Column("is_published", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(btrim(name)) > 0", name=op.f("ck_assessments_name_not_blank")),
        sa.CheckConstraint("max_marks > 0", name=op.f("ck_assessments_max_marks_positive")),
        sa.CheckConstraint("sequence_no > 0", name=op.f("ck_assessments_sequence_positive")),
        sa.CheckConstraint(
            "weightage >= 0 AND weightage <= 100", name=op.f("ck_assessments_weightage_range")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_assessments_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["offering_id"],
            ["course_offerings.id"],
            name=op.f("fk_assessments_offering_id_course_offerings"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessments")),
        sa.UniqueConstraint(
            "offering_id", "sequence_no", name=op.f("uq_assessments_offering_id_sequence_no")
        ),
    )
    op.create_index(
        "uq_assessments_offering_name",
        "assessments",
        ["offering_id", sa.literal_column("lower(name)")],
        unique=True,
    )
    op.create_table(
        "audit_logs",
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("entity", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("old_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("new_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("offering_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["offering_id"],
            ["course_offerings.id"],
            name=op.f("fk_audit_logs_offering_id_course_offerings"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(op.f("ix_audit_logs_actor_id"), "audit_logs", ["actor_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_entity_entity_id"), "audit_logs", ["entity", "entity_id"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_offering_id"), "audit_logs", ["offering_id"], unique=False)
    op.create_table(
        "assessment_results",
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("score", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column(
            "status", sa.Enum("present", "absent", "exempt", name="result_status"), nullable=False
        ),
        sa.Column("max_marks_snapshot", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("source", sa.Enum("manual", "import", name="result_source"), nullable=False),
        sa.Column("recorded_by_id", sa.Uuid(), nullable=True),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'present') = (score IS NOT NULL)",
            name=op.f("ck_assessment_results_score_matches_status"),
        ),
        sa.CheckConstraint(
            "max_marks_snapshot > 0", name=op.f("ck_assessment_results_max_marks_snapshot_positive")
        ),
        sa.CheckConstraint(
            "score IS NULL OR (score >= 0 AND score <= max_marks_snapshot)",
            name=op.f("ck_assessment_results_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
            name=op.f("fk_assessment_results_assessment_id_assessments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_id"],
            ["users.id"],
            name=op.f("fk_assessment_results_recorded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_assessment_results_student_id_students"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("student_id", "assessment_id", name=op.f("pk_assessment_results")),
    )
    op.create_index(
        op.f("ix_assessment_results_assessment_id"),
        "assessment_results",
        ["assessment_id"],
        unique=False,
    )
    # Rename (keeps existing values) rather than drop + add.
    op.drop_constraint(
        op.f("ck_course_offerings_pass_mark_range"), "course_offerings", type_="check"
    )
    op.alter_column(
        "course_offerings",
        "pass_mark_percent",
        new_column_name="pass_percent",
        server_default=sa.text("50.00"),
    )
    op.create_check_constraint(
        op.f("ck_course_offerings_pass_percent_range"),
        "course_offerings",
        "pass_percent >= 0 AND pass_percent <= 100",
    )
    op.add_column(
        "course_offerings",
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.create_check_constraint(
        op.f("ck_course_offerings_config_is_object"),
        "course_offerings",
        "jsonb_typeof(config) = 'object'",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_course_offerings_config_is_object"), "course_offerings", type_="check"
    )
    op.drop_column("course_offerings", "config")
    op.drop_constraint(
        op.f("ck_course_offerings_pass_percent_range"), "course_offerings", type_="check"
    )
    op.alter_column(
        "course_offerings",
        "pass_percent",
        new_column_name="pass_mark_percent",
        server_default=sa.text("40.00"),
    )
    op.create_check_constraint(
        op.f("ck_course_offerings_pass_mark_range"),
        "course_offerings",
        "pass_mark_percent >= 0 AND pass_mark_percent <= 100",
    )
    op.drop_index(op.f("ix_assessment_results_assessment_id"), table_name="assessment_results")
    op.drop_table("assessment_results")
    op.drop_index(op.f("ix_audit_logs_offering_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_entity_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index("uq_assessments_offering_name", table_name="assessments")
    op.drop_table("assessments")
    op.drop_table("settings")
    for enum_name in ("assessment_type", "result_status", "result_source"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
