"""Attention flag persistence (D6) and interventions with targets and reasons (D5).

Flags are resolved rather than deleted when they stop firing, so history survives a
recompute; the partial unique index keeps at most one live flag per (student, rule).

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-29 14:09:52.832845
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interventions",
        sa.Column("offering_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "academic_support",
                "remedial_session",
                "faculty_meeting",
                "peer_support",
                "additional_practice",
                "counselling_referral",
                "other",
                name="intervention_kind",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("planned", "active", "completed", "cancelled", name="intervention_status"),
            server_default="completed",
            nullable=False,
        ),
        sa.Column("after_sequence_no", sa.Integer(), nullable=False),
        sa.Column("recorded_on", sa.Date(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("recorded_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "after_sequence_no >= 0", name=op.f("ck_interventions_after_sequence_no_non_negative")
        ),
        sa.CheckConstraint(
            "note IS NULL OR length(btrim(note)) > 0", name=op.f("ck_interventions_note_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["offering_id"],
            ["course_offerings.id"],
            name=op.f("fk_interventions_offering_id_course_offerings"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_id"],
            ["users.id"],
            name=op.f("fk_interventions_recorded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interventions")),
    )
    op.create_index(
        op.f("ix_interventions_offering_id"), "interventions", ["offering_id"], unique=False
    )
    op.create_table(
        "attention_flags",
        sa.Column("offering_id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column(
            "rule_code",
            sa.Enum(
                "R1_LOW_PERFORMANCE",
                "R2_FAILED_LATEST",
                "R3_REPEATED_LOW",
                "R4_SHARP_DECLINE",
                "R5_DECLINING_TREND",
                "R6_LOW_COMPLETION",
                "R7_BORDERLINE",
                name="attention_rule_code",
            ),
            nullable=False,
        ),
        sa.Column(
            "severity", sa.Enum("high", "medium", "low", name="flag_severity"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("open", "acknowledged", "resolved", name="flag_status"),
            server_default="open",
            nullable=False,
        ),
        sa.Column("actual_value", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column(
            "actual_unit",
            sa.Enum(
                "percent",
                "percentage_points",
                "percentage_points_per_assessment",
                "count",
                "marks",
                name="measure_unit",
            ),
            nullable=False,
        ),
        sa.Column("actual_n", sa.Integer(), nullable=False),
        sa.Column(
            "threshold_key",
            sa.Enum(
                "low_performance_percent",
                "high_performance_percent",
                "repeated_low_count",
                "decline_drop_pp",
                "trend_delta_pp",
                "low_completion_percent",
                "borderline_band_pp",
                "cohort_shift_pp",
                "improvement_delta_pp",
                "min_group_n",
                "min_trend_points",
                "min_consistency_points",
                "min_outcome_group_n",
                name="threshold_key",
            ),
            nullable=True,
        ),
        sa.Column("threshold_value", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column(
            "threshold_source",
            sa.Enum(
                "offering_override", "department_setting", "system_default", name="threshold_source"
            ),
            nullable=True,
        ),
        sa.Column("pass_mark_percent", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "reference_assessments",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("triggered_by_assessment_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'resolved') = (resolved_at IS NOT NULL)",
            name=op.f("ck_attention_flags_resolved_at_matches_status"),
        ),
        sa.CheckConstraint("actual_n >= 0", name=op.f("ck_attention_flags_actual_n_non_negative")),
        sa.CheckConstraint(
            "length(btrim(message)) > 0", name=op.f("ck_attention_flags_message_not_blank")
        ),
        sa.CheckConstraint(
            "threshold_key IS NOT NULL OR pass_mark_percent IS NOT NULL",
            name=op.f("ck_attention_flags_states_its_comparison"),
        ),
        sa.CheckConstraint(
            "threshold_key IS NULL OR (threshold_value IS NOT NULL AND threshold_source IS NOT NULL)",
            name=op.f("ck_attention_flags_threshold_complete"),
        ),
        sa.ForeignKeyConstraint(
            ["offering_id"],
            ["course_offerings.id"],
            name=op.f("fk_attention_flags_offering_id_course_offerings"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_attention_flags_student_id_students"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by_assessment_id"],
            ["assessments.id"],
            name=op.f("fk_attention_flags_triggered_by_assessment_id_assessments"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attention_flags")),
    )
    op.create_index(
        "ix_attention_flags_offering_id_status",
        "attention_flags",
        ["offering_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attention_flags_student_id"), "attention_flags", ["student_id"], unique=False
    )
    op.create_index(
        "uq_attention_flags_offering_id_student_id_rule_code_live",
        "attention_flags",
        ["offering_id", "student_id", "rule_code"],
        unique=True,
        postgresql_where=sa.text("status <> 'resolved'"),
    )
    op.create_table(
        "intervention_students",
        sa.Column("intervention_id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["intervention_id"],
            ["interventions.id"],
            name=op.f("fk_intervention_students_intervention_id_interventions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_intervention_students_student_id_students"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "intervention_id", "student_id", name=op.f("pk_intervention_students")
        ),
    )
    op.create_index(
        op.f("ix_intervention_students_student_id"),
        "intervention_students",
        ["student_id"],
        unique=False,
    )
    op.create_table(
        "intervention_reasons",
        sa.Column("intervention_id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column(
            "rule_code",
            sa.Enum(
                "R1_LOW_PERFORMANCE",
                "R2_FAILED_LATEST",
                "R3_REPEATED_LOW",
                "R4_SHARP_DECLINE",
                "R5_DECLINING_TREND",
                "R6_LOW_COMPLETION",
                "R7_BORDERLINE",
                name="attention_rule_code",
            ),
            nullable=True,
        ),
        sa.Column(
            "finding",
            sa.Enum("sharp_decline", "repeated_low", "improvement", name="student_finding_code"),
            nullable=True,
        ),
        sa.Column("observed_value", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column(
            "observed_unit",
            sa.Enum(
                "percent",
                "percentage_points",
                "percentage_points_per_assessment",
                "count",
                "marks",
                name="measure_unit",
            ),
            nullable=True,
        ),
        sa.Column("observed_n", sa.Integer(), nullable=True),
        sa.Column(
            "threshold_key",
            sa.Enum(
                "low_performance_percent",
                "high_performance_percent",
                "repeated_low_count",
                "decline_drop_pp",
                "trend_delta_pp",
                "low_completion_percent",
                "borderline_band_pp",
                "cohort_shift_pp",
                "improvement_delta_pp",
                "min_group_n",
                "min_trend_points",
                "min_consistency_points",
                "min_outcome_group_n",
                name="threshold_key",
            ),
            nullable=True,
        ),
        sa.Column("threshold_value", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column(
            "threshold_source",
            sa.Enum(
                "offering_override", "department_setting", "system_default", name="threshold_source"
            ),
            nullable=True,
        ),
        sa.Column(
            "assessments",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("source_flag_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "note IS NULL OR length(btrim(note)) > 0",
            name=op.f("ck_intervention_reasons_note_not_blank"),
        ),
        sa.CheckConstraint(
            "observed_value IS NULL OR (observed_unit IS NOT NULL AND observed_n IS NOT NULL)",
            name=op.f("ck_intervention_reasons_observed_complete"),
        ),
        sa.CheckConstraint(
            "rule_code IS NOT NULL OR finding IS NOT NULL OR note IS NOT NULL",
            name=op.f("ck_intervention_reasons_says_something"),
        ),
        sa.CheckConstraint(
            "threshold_key IS NULL OR (threshold_value IS NOT NULL AND threshold_source IS NOT NULL)",
            name=op.f("ck_intervention_reasons_threshold_complete"),
        ),
        sa.ForeignKeyConstraint(
            ["intervention_id", "student_id"],
            ["intervention_students.intervention_id", "intervention_students.student_id"],
            name="fk_intervention_reasons_target",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_flag_id"],
            ["attention_flags.id"],
            name=op.f("fk_intervention_reasons_source_flag_id_attention_flags"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_intervention_reasons")),
    )
    op.create_index(
        op.f("ix_intervention_reasons_intervention_id"),
        "intervention_reasons",
        ["intervention_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_intervention_reasons_intervention_id"), table_name="intervention_reasons"
    )
    op.drop_table("intervention_reasons")
    op.drop_index(op.f("ix_intervention_students_student_id"), table_name="intervention_students")
    op.drop_table("intervention_students")
    op.drop_index(
        "uq_attention_flags_offering_id_student_id_rule_code_live",
        table_name="attention_flags",
        postgresql_where=sa.text("status <> 'resolved'"),
    )
    op.drop_index(op.f("ix_attention_flags_student_id"), table_name="attention_flags")
    op.drop_index("ix_attention_flags_offering_id_status", table_name="attention_flags")
    op.drop_table("attention_flags")
    op.drop_index(op.f("ix_interventions_offering_id"), table_name="interventions")
    op.drop_table("interventions")
    for enum_name in (
        "attention_rule_code",
        "flag_severity",
        "flag_status",
        "measure_unit",
        "threshold_key",
        "threshold_source",
        "intervention_kind",
        "intervention_status",
        "student_finding_code",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
