"""Organization: departments, terms, courses, sections, offerings, faculty assignment;
users.department_id with HOD-requires-department check.

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-26
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "academic_terms",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("academic_year", sa.String(length=9), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("is_current", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "code = upper(code) AND length(code) > 0", name=op.f("ck_academic_terms_code_upper")
        ),
        sa.CheckConstraint("end_date > start_date", name=op.f("ck_academic_terms_dates_ordered")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_academic_terms")),
        sa.UniqueConstraint("code", name=op.f("uq_academic_terms_code")),
    )
    op.create_index(
        "uq_academic_terms_single_current",
        "academic_terms",
        ["is_current"],
        unique=True,
        postgresql_where=sa.text("is_current"),
    )
    op.create_table(
        "departments",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "code = upper(code) AND length(code) > 0", name=op.f("ck_departments_code_upper")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_departments")),
        sa.UniqueConstraint("code", name=op.f("uq_departments_code")),
    )
    op.create_table(
        "courses",
        sa.Column("department_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("credits", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "code = upper(code) AND length(code) > 0", name=op.f("ck_courses_code_upper")
        ),
        sa.CheckConstraint(
            "credits IS NULL OR (credits >= 0 AND credits <= 30)",
            name=op.f("ck_courses_credits_range"),
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_courses_department_id_departments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_courses")),
        sa.UniqueConstraint("code", name=op.f("uq_courses_code")),
    )
    op.create_index(op.f("ix_courses_department_id"), "courses", ["department_id"], unique=False)
    op.create_table(
        "sections",
        sa.Column("department_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("batch_year", sa.Integer(), nullable=False),
        sa.Column("program", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "batch_year BETWEEN 2000 AND 2100", name=op.f("ck_sections_batch_year_range")
        ),
        sa.CheckConstraint("length(name) > 0", name=op.f("ck_sections_name_not_blank")),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_sections_department_id_departments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sections")),
        sa.UniqueConstraint(
            "department_id",
            "batch_year",
            "name",
            name=op.f("uq_sections_department_id_batch_year_name"),
        ),
    )
    op.create_index(op.f("ix_sections_department_id"), "sections", ["department_id"], unique=False)
    op.create_table(
        "course_offerings",
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("term_id", sa.Uuid(), nullable=False),
        sa.Column("section_id", sa.Uuid(), nullable=False),
        sa.Column(
            "pass_mark_percent",
            sa.Numeric(precision=5, scale=2),
            server_default=sa.text("40.00"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "pass_mark_percent >= 0 AND pass_mark_percent <= 100",
            name=op.f("ck_course_offerings_pass_mark_range"),
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_course_offerings_course_id_courses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
            name=op.f("fk_course_offerings_section_id_sections"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["academic_terms.id"],
            name=op.f("fk_course_offerings_term_id_academic_terms"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_course_offerings")),
        sa.UniqueConstraint(
            "course_id",
            "term_id",
            "section_id",
            name=op.f("uq_course_offerings_course_id_term_id_section_id"),
        ),
    )
    op.create_index(
        op.f("ix_course_offerings_course_id"), "course_offerings", ["course_id"], unique=False
    )
    op.create_index(
        op.f("ix_course_offerings_section_id"), "course_offerings", ["section_id"], unique=False
    )
    op.create_index(
        op.f("ix_course_offerings_term_id"), "course_offerings", ["term_id"], unique=False
    )
    op.create_table(
        "offering_faculty",
        sa.Column("offering_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["offering_id"],
            ["course_offerings.id"],
            name=op.f("fk_offering_faculty_offering_id_course_offerings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_offering_faculty_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("offering_id", "user_id", name=op.f("pk_offering_faculty")),
    )
    op.create_index(
        op.f("ix_offering_faculty_user_id"), "offering_faculty", ["user_id"], unique=False
    )
    op.add_column("users", sa.Column("department_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_users_department_id"), "users", ["department_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_users_department_id_departments"),
        "users",
        "departments",
        ["department_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_check_constraint(
        op.f("ck_users_hod_has_department"), "users", "role <> 'HOD' OR department_id IS NOT NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_users_hod_has_department"), "users", type_="check")
    op.drop_constraint(op.f("fk_users_department_id_departments"), "users", type_="foreignkey")
    op.drop_index(op.f("ix_users_department_id"), table_name="users")
    op.drop_column("users", "department_id")
    op.drop_index(op.f("ix_offering_faculty_user_id"), table_name="offering_faculty")
    op.drop_table("offering_faculty")
    op.drop_index(op.f("ix_course_offerings_term_id"), table_name="course_offerings")
    op.drop_index(op.f("ix_course_offerings_section_id"), table_name="course_offerings")
    op.drop_index(op.f("ix_course_offerings_course_id"), table_name="course_offerings")
    op.drop_table("course_offerings")
    op.drop_index(op.f("ix_sections_department_id"), table_name="sections")
    op.drop_table("sections")
    op.drop_index(op.f("ix_courses_department_id"), table_name="courses")
    op.drop_table("courses")
    op.drop_table("departments")
    op.drop_index(
        "uq_academic_terms_single_current",
        table_name="academic_terms",
        postgresql_where=sa.text("is_current"),
    )
    op.drop_table("academic_terms")
    # ### end Alembic commands ###
